[#1]
== クライアント・クレデンシャルズフローの実践
前のセクションまでは、OIDCの認可コードフローをやってきました。

このセクションでは、OIDCをクライアント・クレデンシャルズフローで、アクセストークンを取得するまでを実践します。

クライアント・クレデンシャルズフローは、人が介在せずに、アプリ間のアプリケーション間で認証および認可が必要な場合に使います。
また、APIゲートウェイとバックエンドのアプリケーションの場合などは、このフローを利用します。


[#2]
=== クライアント・クレデンシャルズフローの設定

RH-SSOの管理画面で、アクセストークンを発行するためだけのアプリケーション設定を実施します。

<1> RH-SSOの管理画面に、Adminでログインします。

<2> 左メニューの `Clients` を開きます。

<3> `account`　をクリックします。

<4> `Settings` のタブのAccess Typeの項目のプルダウンを `public` から `confidential` に変更します。

<5> `Settings` のタブのService Accounts Enabled の項目を OFFからON に変更します。 (これで、クライアント・クレデンシャルズフローが有効になります)

<6> 画面の一番下にある `Save`　をクリックします。

=== アクセストークンの取得

RH-SSOに直接curlコマンドを使って、RH-SSOのトークンエンドポイントにアクセスし、アクセストークンを取得します。

RH-SSOのトークンエンドポイントは、以下の形式で定まっています。

"https://<RH-SSOサーバ>/auth/realms/<レルム名>/protocol/openid-connect/token" 

トークンエンドポイントのアクセスには、クライアントIDとクライアントシークレットが必要になります。
それぞれの値を確認します。

<1> RH-SSOの管理画面に、Adminでログインします。

<2> 左メニューの `Clients` を開きます。

<3> `account`　をクリックします。

<4> `Settings` のタブの上部に表示されている Client IDの値が　クライアントIDになります。(今回は、account)

<4> `Credentials` のタブをクリックして移動します

<５> `Credentials`　のSercertの値が　クライアントシークレットになります。(環境によって値は異なります。例： f0af9e5f-68b3-4278-b3c9-e6e496fb5310)


開発環境の画面に移動し、ターミナルで以下を実行します。
環境変数には、さきほど確認したクライアントシークレットの値を入力します。

[source, bash,role="copypaste"]
```
export CLIENT_CREDENTIALS=<クライアントシークレットの値> 
```
例： export CLIENT_CREDENTIALS=f0af9e5f-68b3-4278-b3c9-e6e496fb5310

curlでアクセストークンを取得します。
[source, bash,role="copypaste"]
```
curl \
  -d  client_id=account \
  -d  client_secret=${CLIENT_CREDENTIALS} \
  -d grant_type=client_credentials \
  https://sso-user1-keycloak.apps.cluster-sk7wz.sk7wz.sandbox1045.opentlc.com/auth/realms/demojs/protocol/openid-connect/token
```





