[#openid-claims]
== トークンへのクレーム(属性)の追加
前のセクションでは、js-consoleアプリを作成し、アプリをOIDC(認可コード)の設定をしました。
本セクションでは、トークンにクレームを追加します。
トークンにクレームを追加することで、アプリ側で細かい認可の設定が可能になります。(実際は、アプリ側でクレームの内容を処理する必要があります)

[#openid-client-scopes]
=== クライアントスコープとは？
組織内などで保護および登録する必要のあるアプリケーションが多数ある場合、これらのアプリケーションごとにRH-SSOで設定するのは面倒になることがあります。
RH-SSO では、クライアントスコープと呼ばれ機能で共有設定を定義することができます。

今回は、ユーザ情報にアバターを追加して、アプリにアバターを表示させます。

<1> RH-SSOの管理画面に、Adminでログインします。

<2> 左メニューの `Users` を開きます。

<3> `View all users`　をクリックします。

<4> `Attributes` タブをクリックし、 Keyに `avatar_url` を入力 

<5> `value`　に https://www.keycloak.org/resources/images/keycloak_logo_200px.svg を入力します

<6> `Save` をクリックします。

ユーザの属性に、アバターを設定したので、次はアプリケーション側を設定して、トークンに追加されるようにします。

- 左メニューの `Client Scopes` を開いて、 `Create` をクリックします。

以下の値を入力します:

    Name: avatar
    Consent Screen Text: Avatar

- `Save` をクリックします。
- 　同じ画面上にある `Mappers` をクリックして、 `Create` をクリックします。

以下の値を入力します:

    Name: avatar
    Mapper Type: User Attribute
    User Attribute avatar_url
    Token Claim Name: avatar_url
    Claim JSON Type: String

- `Save` をクリックします。

クライアントスコープを作成しましたが、これは共通定義なので、アプリケーションの `js-console` にも変更を反映させる必要があります。

- 左メニューの `Clients` を開いて、 `js-console` をクリックし、 `Client Scopes` タブをクリックします。

- Default Client Scopeとして追加することにします。ここで `avatar` をクリックし、 `Add selected` をクリックします。デフォルトのスコープなので、デフォルトでトークンに追加されます。

- 次に、JS Consoleのアプリに戻り、 `refresh` をクリックします。JS Consoleのメインダッシュボードにアバターとしてkeycloakのロゴが表示されます。

- `Access Token JSON`　をクリックすると、トークンに追加された内容も表示されます。 以下は、 `Access Token JSON`　の追加された行です。

[source, json]
----
"avatar_url": "https://www.keycloak.org/resources/images/keycloak_logo_200px.svg",

----
